name: "container permission squashed"
description: "Change all permissions in a container to be owned by root (for Podman driver)"
inputs:
  container:
    description: the container URI to port (already built)
    required: true
  squashed:
    description: the squashed container URI
    required: true

runs:
  using: "composite"
  steps:
    - name: Squash
      env:
        action_path: ${{ github.action_path }}
        container: ${{ inputs.container }}
        squashed: ${{ inputs.squashed }}
      run: /bin/bash ${action_path}/scripts/squash.sh ${container} ${squashed}
      shell: bash
