name: Build Deploy Squashed Containers

on:

  # Publish packages on release
  release:
    types: [published]

  # Test on pull request
  pull_request: []

  # On push to main we build and deploy images
  push:
    branches:
    - main

jobs:
  build:
    permissions:
      packages: write

    # This is the container URI without a tag
    env:
      container: ghcr.io/vsoch/container
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Regular Container
      run: docker build -t ${{ env.container }}:latest .

    - name: Squash Container
      uses: rse-ops/container-permission-squasher@main
      with:
        container: ${{ env.container }}:latest
        squashed: ${{ env.container }}:squashed

    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and Push Release Image
      if: (github.event_name == 'release')
      run: |
        tag=${GITHUB_REF#refs/tags/}
        echo "Tagging and releasing ${{ env.container }}:${tag}"
        docker tag ${{ env.container }}:latest ${{ env.container }}:${tag}
        docker push ${{ env.container }}:${tag}

    - name: Deploy
      if: (github.event_name != 'pull_request')
      run: |
        docker push ${{ env.container }}:latest
        docker push ${{ env.container }}:squashed
